# Generated by Django 5.1.1 on 2024-10-28 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.CharField(max_length=64, unique=True),
            preserve_default=False,
        ),
    ]