name: Testing
on: push

jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        # Set up enviroment variables for DB connection
        - name: Set up environment variables
          run: |
            echo "DB_ENGINE=django.db.backends.postgresql" >> $GITHUB_ENV
            echo "DB_DATABASE=test_db" >> $GITHUB_ENV
            echo "DB_USERNAME=test_user" >> $GITHUB_ENV
            echo "DB_PASSWORD=test_password" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_PORT=5432" >> $GITHUB_ENV


        # Install dependencies
        - name: Install dependencies
          run: pip3 install -r requirements.txt

        # Run tests
        - name: Run Django unit tests
          run: |
            pip3 install --user django
            python3 manage.py test