# Generated by Django 5.1.1 on 2024-09-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PorductIngredient',
            new_name='ProductIngredient',
        ),
    ]
