# Generated by Django 5.1.1 on 2024-09-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_ingredient_seller_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_measure',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='size',
        ),
    ]
