# Generated by Django 5.1.1 on 2024-09-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_ingredients_productingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_price',
            new_name='subtotal_price',
        ),
    ]
