# Generated by Django 5.1.1 on 2024-10-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_total_price_product_subtotal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
