# Generated by Django 5.1.1 on 2024-10-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_ingredient_deleted_at_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
