# Generated by Django 5.1.1 on 2024-10-28 04:36

from django.db import migrations
from ..models import Category

def create_categories(apps, schema_editor):

    Category.objects.create(name="Cakes", image="cake1")
    Category.objects.create(name="Bakery", image="croissant")
    Category.objects.create(name="Pies", image="pie")
    Category.objects.create(name="Cookies", image="cookie")
    Category.objects.create(name="Cupcakes", image="cupcake")
    Category.objects.create(name="Desserts", image="dessert")
    Category.objects.create(name="Vegan", image="fruit")
    Category.objects.create(name="Specialty Cakes", image="cake2")


def reverse_create_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.filter(name__in=[
        "Cakes", "Bakery", "Pies", "Cookies", "Cupcakes", "Desserts", "Vegan", "Specialty Cakes"
    ]).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('products', '0013_category_image'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_create_categories),
    ]
